/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutMode: typeof import('./src/components/preference/layout-mode.vue')['default']
    Preference: typeof import('./src/components/preference/index.vue')['default']
    ProLayout: typeof import('pro-naive-ui')['ProLayout']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
