/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/app-provider/index.vue')['default']
    Footer: typeof import('./src/components/layout/footer.vue')['default']
    HeaderCenter: typeof import('./src/components/layout/header-center.vue')['default']
    HeaderLeft: typeof import('./src/components/layout/header-left.vue')['default']
    HeaderRight: typeof import('./src/components/layout/header-right.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutMode: typeof import('./src/components/preference/layout-mode.vue')['default']
    LayoutPreference: typeof import('./src/components/preference-drawer/layout-preference.vue')['default']
    Logo: typeof import('./src/components/layout/logo.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NFlex: typeof import('naive-ui')['NFlex']
    NIcon: typeof import('naive-ui')['NIcon']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    Preference: typeof import('./src/components/preference/index.vue')['default']
    PreferenceDrawer: typeof import('./src/components/preference-drawer/index.vue')['default']
    ProButton: typeof import('pro-naive-ui')['ProButton']
    ProConfigProvider: typeof import('pro-naive-ui')['ProConfigProvider']
    ProLayout: typeof import('pro-naive-ui')['ProLayout']
    ProLayoutyoyo: typeof import('pro-naive-ui')['ProLayoutyoyo']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/sidebar.vue')['default']
    SidebarExtra: typeof import('./src/components/layout/sidebar-extra.vue')['default']
    Tabbar: typeof import('./src/components/layout/tabbar.vue')['default']
    ThemePreference: typeof import('./src/components/preference-drawer/theme-preference.vue')['default']
  }
}
